trial_controller_velocity:
    type: trial_controller_velocity/TrialControllerVelocity
    m_tr: 5
    m_rot: 0.1
    d_tr: 10
    d_rot: 0.4
    only_transl: false
    only_x: false
    only_damping: false
    small_mass: true
    m_tr_no_mass: 5
    m_rot_no_mass: 0.1
    d_tr_no_mass: 50
    d_rot_no_mass: 5
